name: SuperLinter CI

on:
  pull_request:
    branches: ['master']
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint CodeBase
        uses: github/super-linter@v4.9.6
        env:
          LINTER_RULES_PATH: /
          TYPESCRIPT_ES_CONFIG_FILE: .eslintrc
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: 'master'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
